apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-alias: webapp.kroger.com
spec:
  tls:
    - hosts:
      #hostname of your application
      - webapp.tooling.rch-cdc-cxnonprod.kroger.com
      #certificate secret (created by provisioning)
      secretName: star-tooling-hdccxnonprod
  rules:
    - host: webapp.tooling.rch-cdc-cxnonprod.kroger.com
      http:
        paths:
        - path: /
          backend:
            # This assumes http-svc exists and routes to healthy endpoints
            serviceName: webapp-frontend
            servicePort: 80