apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-webapp-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-webapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: spring-boot-webapp
    spec:
      containers:
      - name: spring-boot-webapp
        image: docker-dev.registry.kroger.com/tools/spring-boot-webapp:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: CONFIG_VAR
          value: config_value
        - name: SECRET_VAR
          valueFrom:
            secretKeyRef:
              # refer to secret created by azure/k8s-create-secret GitHub Action
              name: spring-boot-webapp-secret
              key: application-secret
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-webapp-frontend
  labels:
    app: spring-boot-webapp
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      #targetPort: 80
  selector:
    app: spring-boot-webapp
